[2024-03-29T16:24:01.829-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dados-combustivel.carga manual__2024-03-29T18:07:19.604586+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
